# Generated by Django 5.0.6 on 2025-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name_of_action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meaning', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
                ('topics', models.ManyToManyField(related_name='actions', to='action.topic')),
            ],
        ),
    ]
