# Generated by Django 5.0.6 on 2025-03-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_actor_action_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='actors',
            field=models.ManyToManyField(related_name='actions', to='action.actor'),
        ),
    ]
