# Generated by Django 5.0.6 on 2025-03-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_alter_action_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='type_of_action',
        ),
        migrations.AddField(
            model_name='action',
            name='type_of_action',
            field=models.ManyToManyField(related_name='actions', to='action.typeofaction'),
        ),
    ]
