# Generated by Django 5.0.6 on 2025-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_typeofaction_remove_action_type_of_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
