# Generated by Django 5.0.6 on 2025-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_alter_action_name_of_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
