# Generated by Django 5.0.6 on 2025-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_alter_action_description_alter_action_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='source',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
