# Generated by Django 5.0.6 on 2025-03-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0009_remove_action_news_commentary_action_news_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='challenge_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
