# Generated by Django 5.0.6 on 2025-04-07 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0010_action_challenge_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='action.action')),
            ],
        ),
    ]
