# Generated by Django 5.0.6 on 2025-04-07 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_sitevisit_delete_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='total_visits',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
